### ISSUE TITLE
Prompting and Evaluation-Query writing and SQL langchain tutorial learning

### ISSUE THREAD

**Issue by JhanviRana** [BeckResearchLab/llmao#13]

**Comment by ashfen6** [comment]
Continuing to work on writing SQL queries while the model continues to be hosted.

**Comment by mahmoa** [comment]
Now that the model is running, come up with some example questions to determine whether or not the model needs to be fine tuned. Come up with a way to evaluate whether or not the model is sufficiently answering the question (LLM evaluating LLM)

**Comment by JhanviRana** [comment]
Learning SQL langchain tutorial done and query writing done.Prepare example question by each member and tested.
