### ISSUE TITLE
Data Pooling & Querying

### ISSUE THREAD

**Issue by mahmoa** [BeckResearchLab/llmao#4]
Dataset 1. AOP-DB from https://gaftp.epa.gov/EPADataCommons/ORD/AOP-DB/ 
- This is already on Hyak and exists as two .db files which we can query with SQL
- Database schema: https://aopdb.epa.gov/aopws//webContent/schema
- Langchain models can query databases using chains or agents: https://python.langchain.com/docs/use_cases/sql/
Dataset 2. AOP-Wiki from https://aopwiki.org/info_pages/5

Look into both datasets (evaluate any potential new datasets), search through the best way to combine the data for use in the LLM. How to engineer prompts so that the model retrieves the correct data?

**Comment by ashfen6** [comment]
Have successfully queried the AOP database. This can be seen on http://llm-ao.com/DisViz as every diagram generated is querying the database.
