### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by mahmoa** [BeckResearchLab/llmao#5]
Look into the potential options to use for evaluating a LLM:
https://python.langchain.com/docs/guides/evaluation/
Research on cost evaluation for LLMs could also be useful if we want to compare things like runtime or resource usage in the future.

This task could also involve comparing the existing pre-trained models on Langchain and evaluating which ones are most appropriate for us to use: 
https://python.langchain.com/docs/integrations/components

**Comment by nicelmh** [comment]
Just a heads up that the links under "LangSmith Evaluation" in the first link are broken, but further reading on LangSmith is available here: https://docs.smith.langchain.com/ (the "Evaluation" section here has "How-To Guides", including "How to use off-the-shelf LangChain evaluators")
LangSmith cookbook here: https://docs.smith.langchain.com/cookbook

**Comment by nicelmh** [comment]
"For simple queries, such as filtering by project, run time, name, or run ID's, you can directly use keyword arguments in the list_runs method."
https://docs.smith.langchain.com/tracing/faq/querying_traces#using-keyword-arguments

**Comment by ashfen6** [comment]
Have accomplished this task using Langfuse, which is automatically tracking all of the questions asked to the model and scoring every question/answer based on answer relevancy and faithfulness.
